---
title: "Genshin Impact Qualitative Sentiment Analysis"
author: "Will Arangelov"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: united
    orientation: row
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(gt)
library(scales)
library(stringr)
```

```{r data, include = FALSE}

setwd("C:/Users/Administrator/Desktop/EDLD652FinalProj/data")

library(readxl)
edld652data <- read_excel("C:/Users/Administrator/Desktop/EDLD652FinalProj/data/edld652data.xlsx")
View(edld652data)

thematic <- read_excel("C:/Users/Administrator/Desktop/EDLD652FinalProj/data/thematic.xlsx")
View(thematic)

min_t <- read_excel("C:/Users/Administrator/Desktop/EDLD652FinalProj/data/minor_t.xlsx")
view(min_t)
```

```{r manipulations, include = FALSE}
st_per_year <- edld652data %>%
  count(year, sentiment)
print(st_per_year) 

st_per_year_key <- edld652data %>%
  count(year, sentiment, keyword)
print(st_per_year_key)
```

```{r themes, include = FALSE}
smry <- thematic %>%
  group_by(year, theme) %>%
  summarise(count = sum(count), .groups = "drop")
```

```{r minor, include=FALSE}
top_20 <- min_t %>%
  arrange(desc(count)) %>%
  slice_head(n = 20) %>%
  mutate(highlight = ifelse(str_detect(minor_t, "Game"), "Game-related", "Other"))
```

Row {data-height=50%}
-----------------------------------------------------------------------

### Plot A

```{r}
ggplot(st_per_year, aes(x = year, y = n, color = sentiment, group = sentiment)) + 
  geom_line(size = 1.2) + 
  geom_point() +
  scale_color_viridis_d(option = "plasma") +
  labs(
    title = str_wrap("Genshin Impact Player's Sentiments about Representation", width = 40),
    x = "Year",
    y = "Count",
    color = "Sentiment", 
    caption = "Data source: r/Genshin_Impact"
  ) +
  theme_minimal() + 
  theme(
    plot.title = element_text(face = "bold", size = 18, hjust = 0.5),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14)
  )
```


### Plot B

```{r}
ggplot(st_per_year_key, aes(x = year, y = n, color = sentiment, group = sentiment)) + 
  geom_line(size = 1.2) + 
  geom_point(size = 1.5) +
  scale_color_viridis_d(option = "plasma") +
  facet_wrap(~keyword) +
  labs(
    title = str_wrap("Genshin Impact Player's Sentiments per Keyword", width = 40),
    x = "Year",
    y = "Count",
    color = "Sentiment", 
    caption = "Data source: r/Genshin_Impact"
  ) +
  theme_minimal() + 
  theme(
    plot.title = element_text(face = "bold", size = 18, hjust = 0.5),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14), 
    axis.text.x = element_text(angle = 45, hjust = 1))
```

Row {data-height=50%}
-----------------------------------------------------------------------

### Plot C

```{r}
ggplot(smry, aes(x = year, y = theme, fill = count)) +
  geom_tile(color = "white") + 
  scale_fill_gradient(low = "white", high = "red") +
  labs(
    title = "Major Theme Occurance Over Years",
    x = "Year",
    y = "Theme",
    fill = "Usage Count",
    caption = "r/Genshin_Impact"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 18, hjust = 0.5),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

### Plot D

```{r}
ggplot(top_20, aes(x = reorder(minor_t, count), y = count, fill = highlight)) +
  geom_col() +
  scale_fill_viridis_d(option = "C", begin = 0.2, end = 0.8) + 
  coord_flip() + 
  labs(title = "Top 20 Minor Themes",
       x = "Minor Themes", 
       y = "Count",
       fill = "Category",
      caption = "r/Genshin_Impact") +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 18, hjust = 0.5),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14)
  )
```

